### ISSUE TITLE
? instead of crm-namespace

### ISSUE THREAD

**Issue by ksdm2e** [DM2E/pubby#3]
The namespace of crm seems to be unknown:

```
?:P80F.end_is_qualified_by

crm: <http://www.cidoc-crm.org/cidoc-crm/>
```

See: 
http://data.dm2e.eu/data/html/timespan/bbaw/dta/1784-01-01T000000UG_1784-12-31T235959UG

**Comment by kba** [comment]
Just fixed. Will be visible on the next restart.
